#! This shelf to object merges selecte node into a new geometry node

#get path and name of selected node and parent obj
selected = hou.selectedNodes()
nodepath = ""

if len(selected) < 1:
    hou.ui.displayMessage("No Node Selected")
    
else:
    for sel in selected:        
        nodepath = sel.path()
    
    selectedname = hou.node(nodepath)
    parent = str(selectedname.parent())
    
    if parent != "obj":
        nodename = parent
    else:
        nodename = selectedname

    geo = hou.node("/obj").createNode("geo", str(nodename) + "_copy", run_init_scripts=False)
    
    objmerge = geo.createNode("object_merge", str(nodename) + "_" + str(selectedname))
    objmerge.parm("objpath1").set(nodepath)
    objmerge.parm("xformtype").set(1)
    
    p = hou.ui.paneTabOfType(hou.paneTabType.NetworkEditor)
    p.setCurrentNode(objmerge)
    p.homeToSelection()
        
        
#Zybrand Jacobs
